vich_uploader:
    db_driver: orm

    mappings:
        articleIllustrations:
            uri_prefix: /images/blog/articleIllustrations
            upload_destination: '%kernel.project_dir%/public/images/blog/articleIllustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        offerIllustrations:
            uri_prefix: /images/offer_description/offerIllustrations
            upload_destination: '%kernel.project_dir%/public/images/offer_description/offerIllustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        featureIllustrations:
            uri_prefix: /images/offer_description/featureIllustrations
            upload_destination: '%kernel.project_dir%/public/images/offer_description/featureIllustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        userAvatar:
            uri_prefix: /images/user/avatar
            upload_destination: '%kernel.project_dir%/public/images/user/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        clubLogo:
            uri_prefix: /images/club/logo
            upload_destination: '%kernel.project_dir%/public/images/club/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
