vich_uploader:
    db_driver: orm

    mappings:
        articleIllustrations:
            uri_prefix: /images/blog/articleIllustrations
            upload_destination: '%kernel.project_dir%/public/images/blog/articleIllustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        offerIllustrations:
            uri_prefix: /images/offer_description/offerIllustrations
            upload_destination: '%kernel.project_dir%/public/images/offer_description/offerIllustrations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
